# Generated by Django 4.2.4 on 2023-08-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('media_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='NBAStats.media')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('conference_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='NBAStats.conference')),
                ('media_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='NBAStats.media')),
                ('players', models.ManyToManyField(to='NBAStats.players')),
            ],
        ),
    ]
