# Generated by Django 4.2.4 on 2023-08-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0003_media_asset_url_players_apg_players_bpg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='media_id',
        ),
    ]
