# Generated by Django 4.2.4 on 2023-08-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0004_remove_players_media_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='media_id',
        ),
    ]
