# Generated by Django 4.2.4 on 2023-08-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0004_favoriteplayers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteplayers',
            old_name='team_id',
            new_name='player_id',
        ),
    ]
