# Generated by Django 4.2.4 on 2023-08-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0005_remove_teams_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='jersey_number',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
