# Generated by Django 4.2.4 on 2023-08-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0006_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team_id',
        ),
        migrations.AddField(
            model_name='game',
            name='team_id_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_as_team_a', to='NBAStats.teams'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_id_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_as_team_b', to='NBAStats.teams'),
        ),
    ]
