# Generated by Django 4.2.4 on 2023-08-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0007_players_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='jersey_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
