# Generated by Django 4.2.4 on 2023-08-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAStats', '0008_alter_players_jersey_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='jersey_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
